---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks


#these could be helpful to include like the Proxmox, etc access links.
- Developer:
    - Data Ducts Github:
        - abbr: DD
          href: https://github.com/acep-uaf/data-ducts

    - Keeper Security: 
        - abbr: KPR
          href: https://keepersecurity.com/vault/#

    - Authentik:
        - abbr: ANK
          href: https://auth.lab.acep.uaf.edu/if/user/#/library
