---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks


#these could be helpful to include like the Proxmox, etc access links.
- Developer:
    - Data Ducts Github:
        - abbr: DD
          href: https://github.com/acep-uaf/data-ducts

    - Keeper Security: 
        - abbr: KPR
          href: https://keepersecurity.com/vault/#

    - Authentik:
        - abbr: ANK
          href: https://auth.lab.acep.uaf.edu/if/user/#/library

    - ACEP Wiki:
        - abbr: WIKI 
          href: https://wiki.acep.uaf.edu/en/devops/camio

- Basics:
    - Camio Lab Overview Slides:
        - abbr: CLO
          href: https://docs.google.com/presentation/d/1k-Ku94jfimJqoxoJH77_eKMNr16B21Wdeow3iRQWlm0/edit#slide=id.g2e26b00621a_0_9
