---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/bookmarks


#these could be helpful to include like the Proxmox, etc access links.
- Developer:
    - Github:
        - abbr: DD
          href: https://github.com/acep-uaf/data-ducts


