---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- ProxMox Cluster:
    - PVE0:
# Tailscale ping and link
       ping: 100.64.0.24
       href: https://100.64.0.24:8006/
       description: Main server sitting beside the Design Lab FS Switch
       widget:
        type: proxmox

    - PVE1:
        ping: 10.8.0.11
        href: https://10.8.0.11:8006/
        description: In development by John, additional Proxmox to add to cluster
        widget:
          type: proxmox
            
# Added PVE2 2024/10/09
    - PVE2:
        ping: 10.25.159.237
        href: https://10.25.159.237:8006/
        description: Second Proxmox VE Node, currently located within the CAMIO Server Rack
        widget:
          type: proxmox

    - OpnSense:
        ping: 10.3.0.1
        href: https://10.3.0.1/
        description: Firewall
        widget:
          type: opnsense

# The following are items I'd like to include at some point, but not needed right now
#    - Storage Box: 
#        description: work in progress..
#    - OT-Dev:
#        ping: 
#        description: Operational Development box; must be accessed through Bastion
#    - Bastion Box:
#        description: Main jump box to get into Fairbanks CAMIO Lab

- Switches:
    - Design Lab Switch - 0:
        ping: 10.3.0.2
        href: https://10.3.0.2/
        description: connection to the Design Lab switch

    - Dry Lab Switch - 1:
        ping: 10.3.0.3
        href: https://10.3.0.3/
        description: connection to the Dry Lab switch

          #could look at adding checks for the switch being put into the server rack as well as the one for in Dayne's office....just thoughts

#at some point with the camio backup server TrueNAS should be added in here....
- Backups:
    - Storage Box:
        description: running TrueNAS
    - Proxmox Backup Server:
        description: running PBS

