---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- CAMIO Lab:
    - ProxMox - PVE0:
        href: http://localhost/
        description: Homepage is awesome
    - OpnSense:
    - Storage Box: 
    - OT-Dev:
    - Bastion Box:

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
