---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

#title includes
title: Design Lab Dashboard

# background
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  opacity: 50 #0-100
