---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

#title includes
title: Design Lab Dashboard

#Background setup
#doesn't seem to be working....
volumes:
  - /Documents/Github/DesignLab_Dashboard/images

background: /images/denali.jpg

#need to check the above section...



