---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

#title includes
title: Design Lab Dashboard

# background
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  opacity: 75 #0-100

#change card and bookmark blur
cardBlur: sm # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur

headerStyle: underlined


#now to play with formatting and layout
useEqualHeights: true

layout:
 #if I wanted tabs, this is where to put them!
  ProxMox Cluster:
    style: row
    columns: 3

  Switches:
    style: grid
    columns: 1

  Backups:
    style: grid
    columns: 1

