---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

#title includes
title: Design Lab Dashboard

#Background setup
volumes:
  - /Documents/Github/DesignLab_Dashboard/images

background: /images/denali.jpg

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
