---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/settings

#title includes
title: Design Lab Dashboard

# background
background:
  image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
  opacity: 75 #0-100

#change card and bookmark blur
cardBlur: sm # sm, "", md, etc... see https://tailwindcss.com/docs/backdrop-blur

headerStyle: underlined


#now to play with formatting and layout
useEqualHeights: true

layout:
 #if I wanted tabs, this is where to put them!
  
#first, tour and basic overview resources
  Basics:
    tab: CAMIO Basics
    #header: false
    style: grid
    columns: 1
  
  Camio Lab Overview:
    tab: CAMIO Basics

#now actual hardware stats
  ProxMox Cluster:
    tab: CAMIO Resources
    style: row
    columns: 3

  Switches:
    tab: CAMIO Resources
    style: grid
    columns: 1

  Backups:
    tab: CAMIO Resources
    style: grid
    columns: 1

  Other Service Stats:
    tab: CAMIO Resources
    style: grid
    columns: 2

  Helpful Links:
    tab: CAMIO Resources
    style: row
    columns: 2

  Status: 
    tab: CAMIO Resources
    style: row
    column: 2

  
