---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

#- resources:
#    cpu: true
#    memory: true
#    disk: /

#- search:
#    provider: duckduckgo
#    target: _blank


- ProxMox:
  

- Calendar: 
    description: monthly breakdown
    widget:
      type: calendar
      firstDayInWeek: sunday
      view: monthly
      maxEvents: 10
      showTime: true
      integrations:
        - type: sonarr
          service_group: Media
          service_name: Sonarr
          color: teal
          params:
            unmonitored: true
