---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/service-widgets

#- resources:
#    cpu: true
#    memory: true
#    disk: /

- search:
    provider: duckduckgo
    target: _blank

#adding in date and time for reference
- datetime:
    text_size: md
    locale: nl
    format:
      timeStyle: short
      hourCycle: h23
 
#adding in a glance for host computer
- glances:
    cpu: true
    mem: true
    cputemp: true
    uptime: true
    expanded: true
